'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.0.3705.288
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.0.3705.288.
'
Namespace com.efxnow.api
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ServiceSoap", [Namespace]:="https://api.efxnow.com/webservices2.1")>  _
    Public Class Service
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://api.efxnow.com/DemoWebservices2.1/service.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://api.efxnow.com/webservices2.1/GetHistoricRatesDataSet", RequestNamespace:="https://api.efxnow.com/webservices2.1", ResponseNamespace:="https://api.efxnow.com/webservices2.1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetHistoricRatesDataSet(ByVal Key As String, ByVal Quote As String, ByVal StartDateTime As String, ByVal EndDateTime As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("GetHistoricRatesDataSet", New Object() {Key, Quote, StartDateTime, EndDateTime})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginGetHistoricRatesDataSet(ByVal Key As String, ByVal Quote As String, ByVal StartDateTime As String, ByVal EndDateTime As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetHistoricRatesDataSet", New Object() {Key, Quote, StartDateTime, EndDateTime}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetHistoricRatesDataSet(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://api.efxnow.com/webservices2.1/GetAccount", RequestNamespace:="https://api.efxnow.com/webservices2.1", ResponseNamespace:="https://api.efxnow.com/webservices2.1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetAccount(ByVal UserID As String, ByVal PWD As String, ByVal Brand As String) As String
            Dim results() As Object = Me.Invoke("GetAccount", New Object() {UserID, PWD, Brand})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginGetAccount(ByVal UserID As String, ByVal PWD As String, ByVal Brand As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetAccount", New Object() {UserID, PWD, Brand}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetAccount(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://api.efxnow.com/webservices2.1/GetDealBlotter", RequestNamespace:="https://api.efxnow.com/webservices2.1", ResponseNamespace:="https://api.efxnow.com/webservices2.1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetDealBlotter(ByVal Key As String) As String
            Dim results() As Object = Me.Invoke("GetDealBlotter", New Object() {Key})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginGetDealBlotter(ByVal Key As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetDealBlotter", New Object() {Key}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetDealBlotter(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://api.efxnow.com/webservices2.1/GetMarginBlotter", RequestNamespace:="https://api.efxnow.com/webservices2.1", ResponseNamespace:="https://api.efxnow.com/webservices2.1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetMarginBlotter(ByVal Key As String) As String
            Dim results() As Object = Me.Invoke("GetMarginBlotter", New Object() {Key})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginGetMarginBlotter(ByVal Key As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetMarginBlotter", New Object() {Key}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetMarginBlotter(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://api.efxnow.com/webservices2.1/GetOrderBlotter", RequestNamespace:="https://api.efxnow.com/webservices2.1", ResponseNamespace:="https://api.efxnow.com/webservices2.1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetOrderBlotter(ByVal Key As String) As String
            Dim results() As Object = Me.Invoke("GetOrderBlotter", New Object() {Key})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginGetOrderBlotter(ByVal Key As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetOrderBlotter", New Object() {Key}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetOrderBlotter(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://api.efxnow.com/webservices2.1/GetPositionBlotter", RequestNamespace:="https://api.efxnow.com/webservices2.1", ResponseNamespace:="https://api.efxnow.com/webservices2.1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetPositionBlotter(ByVal Key As String) As String
            Dim results() As Object = Me.Invoke("GetPositionBlotter", New Object() {Key})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginGetPositionBlotter(ByVal Key As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetPositionBlotter", New Object() {Key}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetPositionBlotter(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://api.efxnow.com/webservices2.1/GetSymbolBlotter", RequestNamespace:="https://api.efxnow.com/webservices2.1", ResponseNamespace:="https://api.efxnow.com/webservices2.1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetSymbolBlotter(ByVal Key As String) As String
            Dim results() As Object = Me.Invoke("GetSymbolBlotter", New Object() {Key})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginGetSymbolBlotter(ByVal Key As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetSymbolBlotter", New Object() {Key}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetSymbolBlotter(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://api.efxnow.com/webservices2.1/PlaceSingleOrder", RequestNamespace:="https://api.efxnow.com/webservices2.1", ResponseNamespace:="https://api.efxnow.com/webservices2.1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function PlaceSingleOrder(ByVal UserID As String, ByVal PWD As String, ByVal Pair As String, ByVal Expiry As String, ByVal BuySell As String, ByVal Amount As String, ByVal Rate As String, ByVal OrderBasis As String) As objPlaceOrderResponse
            Dim results() As Object = Me.Invoke("PlaceSingleOrder", New Object() {UserID, PWD, Pair, Expiry, BuySell, Amount, Rate, OrderBasis})
            Return CType(results(0),objPlaceOrderResponse)
        End Function
        
        '<remarks/>
        Public Function BeginPlaceSingleOrder(ByVal UserID As String, ByVal PWD As String, ByVal Pair As String, ByVal Expiry As String, ByVal BuySell As String, ByVal Amount As String, ByVal Rate As String, ByVal OrderBasis As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("PlaceSingleOrder", New Object() {UserID, PWD, Pair, Expiry, BuySell, Amount, Rate, OrderBasis}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndPlaceSingleOrder(ByVal asyncResult As System.IAsyncResult) As objPlaceOrderResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),objPlaceOrderResponse)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://api.efxnow.com/webservices2.1/PlaceOCOOrder", RequestNamespace:="https://api.efxnow.com/webservices2.1", ResponseNamespace:="https://api.efxnow.com/webservices2.1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function PlaceOCOOrder(ByVal UserID As String, ByVal PWD As String, ByVal Pair As String, ByVal Expiry As String, ByVal BuySell As String, ByVal Amount As String, ByVal Rate As String, ByVal OrderBasis As String, ByVal BuySell1 As String, ByVal Amount1 As String, ByVal Rate1 As String, ByVal OrderBasis1 As String) As objPlaceOrderResponse
            Dim results() As Object = Me.Invoke("PlaceOCOOrder", New Object() {UserID, PWD, Pair, Expiry, BuySell, Amount, Rate, OrderBasis, BuySell1, Amount1, Rate1, OrderBasis1})
            Return CType(results(0),objPlaceOrderResponse)
        End Function
        
        '<remarks/>
        Public Function BeginPlaceOCOOrder(ByVal UserID As String, ByVal PWD As String, ByVal Pair As String, ByVal Expiry As String, ByVal BuySell As String, ByVal Amount As String, ByVal Rate As String, ByVal OrderBasis As String, ByVal BuySell1 As String, ByVal Amount1 As String, ByVal Rate1 As String, ByVal OrderBasis1 As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("PlaceOCOOrder", New Object() {UserID, PWD, Pair, Expiry, BuySell, Amount, Rate, OrderBasis, BuySell1, Amount1, Rate1, OrderBasis1}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndPlaceOCOOrder(ByVal asyncResult As System.IAsyncResult) As objPlaceOrderResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),objPlaceOrderResponse)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://api.efxnow.com/webservices2.1/CancelOrder", RequestNamespace:="https://api.efxnow.com/webservices2.1", ResponseNamespace:="https://api.efxnow.com/webservices2.1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CancelOrder(ByVal UserID As String, ByVal PWD As String, ByVal OrderConfirmation As String) As objPlaceOrderResponse
            Dim results() As Object = Me.Invoke("CancelOrder", New Object() {UserID, PWD, OrderConfirmation})
            Return CType(results(0),objPlaceOrderResponse)
        End Function
        
        '<remarks/>
        Public Function BeginCancelOrder(ByVal UserID As String, ByVal PWD As String, ByVal OrderConfirmation As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("CancelOrder", New Object() {UserID, PWD, OrderConfirmation}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndCancelOrder(ByVal asyncResult As System.IAsyncResult) As objPlaceOrderResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),objPlaceOrderResponse)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://api.efxnow.com/webservices2.1/DealRequest", RequestNamespace:="https://api.efxnow.com/webservices2.1", ResponseNamespace:="https://api.efxnow.com/webservices2.1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DealRequest(ByVal UserID As String, ByVal PWD As String, ByVal Pair As String, ByVal BuySell As String, ByVal Amount As String, ByVal Rate As String) As objDealResponse
            Dim results() As Object = Me.Invoke("DealRequest", New Object() {UserID, PWD, Pair, BuySell, Amount, Rate})
            Return CType(results(0),objDealResponse)
        End Function
        
        '<remarks/>
        Public Function BeginDealRequest(ByVal UserID As String, ByVal PWD As String, ByVal Pair As String, ByVal BuySell As String, ByVal Amount As String, ByVal Rate As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("DealRequest", New Object() {UserID, PWD, Pair, BuySell, Amount, Rate}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndDealRequest(ByVal asyncResult As System.IAsyncResult) As objDealResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),objDealResponse)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://api.efxnow.com/webservices2.1/Echo", RequestNamespace:="https://api.efxnow.com/webservices2.1", ResponseNamespace:="https://api.efxnow.com/webservices2.1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Echo(ByVal Message As String) As String
            Dim results() As Object = Me.Invoke("Echo", New Object() {Message})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginEcho(ByVal Message As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Echo", New Object() {Message}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndEcho(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://api.efxnow.com/webservices2.1/GetTime", RequestNamespace:="https://api.efxnow.com/webservices2.1", ResponseNamespace:="https://api.efxnow.com/webservices2.1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetTime() As String
            Dim results() As Object = Me.Invoke("GetTime", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginGetTime(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetTime", New Object(-1) {}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetTime(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://api.efxnow.com/webservices2.1/GetRatesServerAuth", RequestNamespace:="https://api.efxnow.com/webservices2.1", ResponseNamespace:="https://api.efxnow.com/webservices2.1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetRatesServerAuth(ByVal UserID As String, ByVal PWD As String, ByVal Brand As String) As String
            Dim results() As Object = Me.Invoke("GetRatesServerAuth", New Object() {UserID, PWD, Brand})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginGetRatesServerAuth(ByVal UserID As String, ByVal PWD As String, ByVal Brand As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetRatesServerAuth", New Object() {UserID, PWD, Brand}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetRatesServerAuth(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://api.efxnow.com/webservices2.1/GetComment", RequestNamespace:="https://api.efxnow.com/webservices2.1", ResponseNamespace:="https://api.efxnow.com/webservices2.1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetComment() As objMarketText
            Dim results() As Object = Me.Invoke("GetComment", New Object(-1) {})
            Return CType(results(0),objMarketText)
        End Function
        
        '<remarks/>
        Public Function BeginGetComment(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetComment", New Object(-1) {}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetComment(ByVal asyncResult As System.IAsyncResult) As objMarketText
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),objMarketText)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://api.efxnow.com/webservices2.1/GetNews", RequestNamespace:="https://api.efxnow.com/webservices2.1", ResponseNamespace:="https://api.efxnow.com/webservices2.1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetNews() As objMarketText
            Dim results() As Object = Me.Invoke("GetNews", New Object(-1) {})
            Return CType(results(0),objMarketText)
        End Function
        
        '<remarks/>
        Public Function BeginGetNews(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetNews", New Object(-1) {}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetNews(ByVal asyncResult As System.IAsyncResult) As objMarketText
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),objMarketText)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://api.efxnow.com/webservices2.1/GetAccountObject", RequestNamespace:="https://api.efxnow.com/webservices2.1", ResponseNamespace:="https://api.efxnow.com/webservices2.1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetAccountObject(ByVal UserID As String, ByVal PWD As String, ByVal Brand As String, ByVal Notes As String) As objAccount
            Dim results() As Object = Me.Invoke("GetAccountObject", New Object() {UserID, PWD, Brand, Notes})
            Return CType(results(0),objAccount)
        End Function
        
        '<remarks/>
        Public Function BeginGetAccountObject(ByVal UserID As String, ByVal PWD As String, ByVal Brand As String, ByVal Notes As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetAccountObject", New Object() {UserID, PWD, Brand, Notes}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetAccountObject(ByVal asyncResult As System.IAsyncResult) As objAccount
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),objAccount)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://api.efxnow.com/webservices2.1")>  _
    Public Class objPlaceOrderResponse
        
        '<remarks/>
        Public Success As Boolean
        
        '<remarks/>
        Public ErrorDescription As String
        
        '<remarks/>
        Public CustomerOrderReference As Integer
        
        '<remarks/>
        Public OrderConfirmation As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://api.efxnow.com/webservices2.1")>  _
    Public Class objAccount
        
        '<remarks/>
        Public Success As Boolean
        
        '<remarks/>
        Public ErrorDescription As String
        
        '<remarks/>
        Public CustCode As String
        
        '<remarks/>
        Public GUID As String
        
        '<remarks/>
        Public Features As Integer
        
        '<remarks/>
        Public BaseCCY As String
        
        '<remarks/>
        Public LastOrderSeq As Integer
        
        '<remarks/>
        Public LastDealSeq As Integer
        
        '<remarks/>
        Public OrderLotSize As Integer
        
        '<remarks/>
        Public MaxOrderPips As Double
        
        '<remarks/>
        Public CancelOrderPips As Double
        
        '<remarks/>
        Public TradeLotSize As Integer
        
        '<remarks/>
        Public MaxTradeLots As Integer
        
        '<remarks/>
        Public TierCount As Integer
        
        '<remarks/>
        Public Tier1MinLots As Integer
        
        '<remarks/>
        Public Tier1MaxLots As Integer
        
        '<remarks/>
        Public Tier1PipDifference As Integer
        
        '<remarks/>
        Public Tier2MinLots As Integer
        
        '<remarks/>
        Public Tier2MaxLots As Integer
        
        '<remarks/>
        Public Tier2PipDifference As Integer
        
        '<remarks/>
        Public Tier3MinLots As Integer
        
        '<remarks/>
        Public Tier3MaxLots As Integer
        
        '<remarks/>
        Public Tier3PipDifference As Integer
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://api.efxnow.com/webservices2.1")>  _
    Public Class objMarketText
        
        '<remarks/>
        Public Success As Boolean
        
        '<remarks/>
        Public ErrorDescription As String
        
        '<remarks/>
        Public Item0 As String
        
        '<remarks/>
        Public Item1 As String
        
        '<remarks/>
        Public Item2 As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://api.efxnow.com/webservices2.1")>  _
    Public Class objDealResponse
        
        '<remarks/>
        Public Success As Boolean
        
        '<remarks/>
        Public ErrorDescription As String
        
        '<remarks/>
        Public Confirmation As String
    End Class
End Namespace
